### ISSUE TITLE
data/owl_image_encoder_patch32.engine file does not exist in the main directory

### ISSUE THREAD

**Issue by enazari** [NVIDIA-AI-IOT/nanoowl#10]
While following the setup guide, I encountered an error when attempting to build the TensorRT engine for the OWL-ViT vision encoder using the provided command:
`python3 -m nanoowl.build_image_encoder_engine data/owl_image_encoder_patch32.engine`

The error message received was:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/owl_image_encoder_patch32.engine'`

suggesting **data/owl_image_encoder_patch32.engine file does not exist in the main directory.**

Thank you.

**Comment by jaybdub** [comment]
Hi @enazari ,

Thanks for reaching out!

Does the **data** directory exist?  If not could you ``mkdir data`` and retry?

Please let me know if this works for you, if so we likely need to update the instructions.

Thanks,
John

**Comment by enazari** [comment]
Hi @jaybdub ,

Creating the data directory resolved the issue.

I do appreciate your quick response and assistance.

Best regards,
Ehsan
